[package]
name = "automl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linfa-linear =  "0.5.0"
linfa-datasets = { version = "0.5.0", features = ["diabetes"] }
linfa-clustering = "0.5.0"
linfa-nn = "0.5.0"
linfa-elasticnet = "0.5.0"
linfa = { version = "0.5.0", features = ["openblas-static"] }
ndarray = "0.15.3"
num-traits = "0.2.14"
