[package]
name = "automl"
version = "0.1.0"
authors = ["Chris McComb <ccmcc2012@gmail.com>"]
description = "AutoML built on top of linfa"
edition = "2021"
readme = "README.md"
repository = "https://github.com/cmccomb/rust-automl"
homepage = "https://github.com/cmccomb/rust-automl"
documentation = "https://docs.rs/automl"
license = "MIT OR Apache-2.0"
keywords = ["machine-learning", "ml", "linfa", "automl"]
categories = ["algorithms", "mathematics", "science"]


[dependencies]
linfa-linear =  "0.5.0"
linfa-datasets = { version = "0.5.0", features = ["diabetes"] }
linfa-clustering = "0.5.0"
linfa-nn = "0.5.0"
linfa-elasticnet = "0.5.0"
linfa = { version = "0.5.0", features = ["openblas-static"] }
ndarray = "0.15.3"
comfy-table = "5.0.0"