[package]
name = "automl"
version = "0.2.3"
authors = ["Chris McComb <ccmcc2012@gmail.com>"]
description = "Automated machine learning for classification and regression"
edition = "2021"
readme = "README.md"
repository = "https://github.com/cmccomb/rust-automl"
homepage = "https://github.com/cmccomb/rust-automl"
documentation = "https://docs.rs/automl"
license = "MIT OR Apache-2.0"
keywords = ["machine-learning", "ml", "ai", "smartcore", "automl"]
categories = ["algorithms", "mathematics", "science"]

[dependencies]
smartcore = "0.2.0"
comfy-table = "5.0.0"
serde = "1.0.130"
bincode = "1.3.3"
ndarray = "0.15.3"
polars = {version = "0.17.0", features = ["ndarray"]}
humantime = "2.1.0"
eframe = "0.15.0"