[package]
name = "automl"
version = "0.2.4"
authors = ["Chris McComb <ccmcc2012@gmail.com>"]
description = "Automated machine learning for classification and regression"
edition = "2021"
readme = "README.md"
repository = "https://github.com/cmccomb/rust-automl"
homepage = "https://github.com/cmccomb/rust-automl"
documentation = "https://docs.rs/automl"
license = "MIT OR Apache-2.0"
keywords = ["machine-learning", "ml", "ai", "smartcore", "automl"]
categories = ["algorithms", "mathematics", "science"]

[dependencies]
smartcore = "0.2.0"
serde = "1.0.130"
bincode = "1.3.3"
itertools = "0.10.1"
comfy-table = {version = "5.0.0", optional = true}
humantime = {version = "2.1.0", optional = true}
ndarray = {version = "0.15.3", optional = true}
polars = {version = "0.17.0", features = ["ndarray"], optional = true}
eframe = {version = "0.15.0", optional = true}

[features]
default = ["display"]
display = ["comfy-table", "humantime"]
nd = ["ndarray"]
gui = ["eframe"]
csv = ["polars", "nd"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]